# Generated by Django 3.2.12 on 2022-08-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='agency.room'),
        ),
    ]
