# Generated by Django 3.2.12 on 2022-08-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_hotelbooking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='start_date',
            new_name='check_out',
        ),
    ]
