# Generated by Django 3.2.12 on 2022-08-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_remove_hotelbooking_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel',
        ),
    ]
