# Generated by Django 3.2.12 on 2022-08-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_remove_hotelbooking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Normal'), (3, 'Good'), (4, 'Excellent')]),
        ),
    ]
