# Generated by Django 3.2.12 on 2022-08-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_hotel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('MN', 'Minsk'), ('BR', 'Brest'), ('VT', 'Vitebsk'), ('MG', 'Mogilev'), ('GM', 'Gomel'), ('GR', 'Grodno')], max_length=2),
        ),
    ]
