# Generated by Django 3.2.12 on 2022-08-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('Minsk', 'MN'), ('Brest', 'BR'), ('Vitebsk', 'VT'), ('Mogilev', 'MG'), ('Gomel', 'GM'), ('Grodno', 'GR')], max_length=10),
        ),
    ]
