# Generated by Django 3.2.12 on 2022-08-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20220826_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
