# Generated by Django 3.2.12 on 2022-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
